--DROP DATABASE KFC
CREATE DATABASE KFC
go
use KFC

CREATE TABLE CUAHANG(
MACH VARCHAR(10) NOT NULL,
TENCH NVARCHAR(50),
DIACHI NVARCHAR(250),
SDT VARCHAR(11)
)
ALTER TABLE CUAHANG ADD CONSTRAINT PK_CUAHANG PRIMARY KEY (MACH)

CREATE TABLE NHANVIEN(
MANV VARCHAR(10) NOT NULL,
MACH VARCHAR(10) NOT NULL,
TENNV NVARCHAR(40),
NGAYVL SMALLDATETIME,
SDT VARCHAR(11)
)
ALTER TABLE NHANVIEN ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANIEN_CUAHANG FOREIGN KEY (MACH) REFERENCES CUAHANG(MACH)

CREATE TABLE KHACHHANG(
MAKH INT NOT NULL,
TENKH NVARCHAR(40) NOT NULL,	
NGAYSINH SMALLDATETIME ,
GIOITINH BIT,
DIACHI NVARCHAR(250),
TINH NVARCHAR(30),
THANHPHO NVARCHAR(30),
SDT NVARCHAR(11),
DOANHSO MONEY,
EMAIL VARCHAR(50),
TAIKHOAN VARCHAR(50),
MATKHAU VARCHAR(30)
)
--drop table KHACHHANG
ALTER TABLE KHACHHANG ADD CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)

CREATE TABLE NHOMMON(
MANHOM VARCHAR(10) NOT NULL,
TENNM NVARCHAR(50),
FOLDER_IMAGE VARCHAR(50)
)
ALTER TABLE NHOMMON ADD CONSTRAINT PK_NHOMMON PRIMARY KEY (MANHOM)

CREATE TABLE BANTHANHPHAN(
MABTP VARCHAR(10) NOT NULL,
TENBTP NVARCHAR(40),
DVT  NVARCHAR(10)
)
ALTER TABLE BANTHANHPHAN ADD CONSTRAINT PK_BANTHANHPHAN PRIMARY KEY (MABTP)


CREATE TABLE MONAN(
MAMON VARCHAR(10) NOT NULL,
MANHOM VARCHAR(10),
TENMON NVARCHAR(50),
GIA INT,
TINHTRANG INT,
HINHANH VARCHAR(200)
)
ALTER TABLE MONAN ADD CONSTRAINT PK_MONAN PRIMARY KEY (MAMON)
ALTER TABLE MONAN ADD CONSTRAINT FK_MONAN_NHOMMON FOREIGN KEY (MANHOM) REFERENCES NHOMMON(MANHOM)


CREATE TABLE CHITIETMONAN(
MAMON VARCHAR(10) NOT NULL,
MABTP VARCHAR(10) NOT NULL,
SL INT
)
ALTER TABLE CHITIETMONAN ADD CONSTRAINT PK_CHITIETMONAN PRIMARY KEY (MAMON,MABTP)
ALTER TABLE CHITIETMONAN ADD CONSTRAINT FK_CHITIETMONAN_MONAN FOREIGN KEY (MAMON) REFERENCES MONAN(MAMON)
ALTER TABLE CHITIETMONAN ADD CONSTRAINT FK_CHITIETMONAN_BANTHANHPHAN FOREIGN KEY (MABTP) REFERENCES BANTHANHPHAN(MABTP)

CREATE TABLE GIOHANG(
MAKH INT NOT NULL,
MAMON VARCHAR(10) NOT NULL,
SL INT
)   
--drop table GIOHANG

ALTER TABLE GIOHANG ADD CONSTRAINT PK_GIOHANG PRIMARY KEY (MAKH,MAMON)
ALTER TABLE GIOHANG ADD CONSTRAINT FK_GIOHANG_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE GIOHANG ADD CONSTRAINT FK_GIOHANG_MONAN FOREIGN KEY (MAMON) REFERENCES MONAN(MAMON)

CREATE TABLE DONDATHANG(
MADDH INT NOT NULL,
MAKH INT NOT NULL,
NGAYDAT DATETIME,
TRIGIA MONEY,
TRANGTHAI INT
)
ALTER TABLE DONDATHANG ADD CONSTRAINT PK_DONDATHANG PRIMARY KEY (MADDH)
ALTER TABLE DONDATHANG ADD CONSTRAINT FK_DONDATHANG_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

CREATE TABLE CTDDH(
MADDH INT NOT NULL,
MAMON VARCHAR(10) NOT NULL,
SL INT,
TRANGTHAI INT
)

CREATE TABLE DELIVERY(
MADDH INT FOREIGN KEY REFERENCES DONDATHANG(MADDH),
TENNN NVARCHAR(40),
DIACHI NVARCHAR(100),
TINH NVARCHAR(50),
THANHPHO NVARCHAR(60),
SDT VARCHAR(50),
EMAIL NVARCHAR(60)
)
ALTER TABLE CTDDH ADD CONSTRAINT PK_CTDDH_MONAN PRIMARY KEY (MADDH,MAMON)
ALTER TABLE CTDDH ADD CONSTRAINT FK_CTDDH_DONDATHANG FOREIGN KEY (MADDH) REFERENCES DONDATHANG(MADDH)
ALTER TABLE CTDDH ADD CONSTRAINT FK_CTDDH_MONAN FOREIGN KEY (MAMON) REFERENCES MONAN(MAMON)

CREATE TABLE HOADON(
SOHD INT NOT NULL,
MADDH INT,
MANV VARCHAR(10),
NGAYXUAT DATETIME,
TRIGIA MONEY
)

ALTER TABLE HOADON ADD CONSTRAINT PK_HOADON PRIMARY KEY (SOHD)
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_DONDATHANG FOREIGN KEY (MADDH) REFERENCES DONDATHANG(MADDH)
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

CREATE TABLE CHITIETHOADON(
SOHD INT NOT NULL,
MAMON VARCHAR(10) NOT NULL,
SL INT
)   

ALTER TABLE CHITIETHOADON ADD CONSTRAINT PK_CHITIETHOADON PRIMARY KEY (SOHD,MAMON)
ALTER TABLE CHITIETHOADON ADD CONSTRAINT FK_CHITIETHOADON_HOADON FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD)
ALTER TABLE CHITIETHOADON ADD CONSTRAINT FK_CHITIETHOADON_MONAN FOREIGN KEY (MAMON) REFERENCES MONAN(MAMON)

Create table LOAITINTUC
(
	MALOAITINTUC INT PRIMARY KEY,
	TENLOAI VARCHAR(20)
)

Create table TINTUC
(
	MATINTUC INT PRIMARY KEY,
	MALOAITINTUC INT FOREIGN KEY REFERENCES LOAITINTUC(MALOAITINTUC),
	TIEUDE NVARCHAR(200),
	MOTANGAN NVARCHAR(500),
	NOIDUNG NVARCHAR(MAX),
	HINHANH VARCHAR(100)
)

--Insert dữ liệu
insert into NHOMMON values('NH01',N'PHẦN ĂN COMBO','images/Menu/Combo')
insert into NHOMMON values('NH02',N'GÀ RÁN & GÀ QUAY','images/Menu/Fried_roasted_chicken')
insert into NHOMMON values('NH03',N'BURGER - CƠM','images/Menu/Burger_rice')
insert into NHOMMON values('NH04',N'THỨC ĂN NHẸ','images/Menu/Snack')
insert into NHOMMON values('NH05',N'TRÁNG MIỆNG & THỨC UỐNG','images/Menu/Dessert_drink')

INSERT INTO MONAN VALUES('MA001','NH01',N'Gà Giòn Cay',80000,100,'images/Menu/Combo/ga-gion-cay.png')
INSERT INTO MONAN VALUES('MA002','NH01',N'Gà Quay Giấy Bạc',81000,50,'images/Menu/Combo/ga-quay-giay-bac.png')
INSERT INTO MONAN VALUES('MA003','NH01',N'Gà Giòn Cay',82000,120,'images/Menu/Combo/ga-quay-tieu.png')
INSERT INTO MONAN VALUES('MA004','NH01',N'Gà Rán Truyền Thống',80000,130,'images/Menu/Combo/ga-ran-truyen-thong.png')
INSERT INTO MONAN VALUES('MA005','NH01',N'Phần Ăn Gia Đình Loại A',100000,70,'images/Menu/Combo/phan-an-gia-dinh-a.png')
INSERT INTO MONAN VALUES('MA006','NH01',N'Phần Ăn Gia Đình Loại B',110000,80,'images/Menu/Combo/phan-an-gia-dinh-b.png')
INSERT INTO MONAN VALUES('MA007','NH01',N'Phần Ăn Trẻ Em',80000,150,'images/Menu/Combo/phan-an-tre-em.png')
INSERT INTO MONAN VALUES('MA008','NH01',N'Phần Ăn Tiết Kiệm',60000,30,'images/Menu/Combo/phan-tiet-kiem.png')

INSERT INTO BANTHANHPHAN VALUES('BTP01',N'GÀ TRUYỀN THỐNG','MIẾNG')
INSERT INTO BANTHANHPHAN VALUES('BTP02',N'GÀ GIÒN CAY','MIẾNG')
INSERT INTO BANTHANHPHAN VALUES('BTP03',N'GÀ GIÒN KHÔNG XƯƠNG','MIẾNG')
INSERT INTO BANTHANHPHAN VALUES('BTP04',N'MIẾNG GÀ QUAY TIÊU','MIẾNG')
INSERT INTO BANTHANHPHAN VALUES('BTP05',N'GÀ QUAY GIẤY BẠC','MIẾNG')
INSERT INTO BANTHANHPHAN VALUES('BTP06',N'KHOAI TÂY CHIÊN (VỪA)','PHẦN')
INSERT INTO BANTHANHPHAN VALUES('BTP07',N'KHOAI TÂY CHIÊN (LỚN)','PHẦN')
INSERT INTO BANTHANHPHAN VALUES('BTP08',N'KHOAI TÂY CHIÊN (ĐẠI)','PHẦN')
INSERT INTO BANTHANHPHAN VALUES('BTP09',N'BẮP CẢI TRỘN (VỪA)','PHẦN')
INSERT INTO BANTHANHPHAN VALUES('BTP10',N'BẮP CẢI TRỘN (LỚN)','PHẦN')
INSERT INTO BANTHANHPHAN VALUES('BTP11',N'BẮP CẢI TRỘN (ĐẠI)','PHẦN')
INSERT INTO BANTHANHPHAN VALUES('BTP12',N'PEPSI','LY')
INSERT INTO BANTHANHPHAN VALUES('BTP13',N'AQUAFINA','CHAI')
INSERT INTO BANTHANHPHAN VALUES('BTP14',N'TWISTER','LON')
INSERT INTO BANTHANHPHAN VALUES('BTP15',N'PHẦN','')
INSERT INTO BANTHANHPHAN VALUES('BTP16',N'CÁI','')

INSERT INTO LOAITINTUC VALUES(1,'News')
INSERT INTO LOAITINTUC VALUES(2,'Promotion')


